# Generated by Django 3.1.5 on 2021-01-18 07:03

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verticals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vert', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj', models.CharField(blank=True, max_length=100, null=True)),
                ('vert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_manage.verticals')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('proj', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='vert', chained_model_field='vert', on_delete=django.db.models.deletion.CASCADE, to='job_manage.projects')),
                ('vert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_manage.verticals')),
            ],
        ),
        migrations.CreateModel(
            name='Joballocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('shift_1_start_time', models.TimeField(blank=True, null=True)),
                ('shift_1_end_time', models.TimeField(blank=True, null=True)),
                ('shift_1_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_2_start_time', models.TimeField(blank=True, null=True)),
                ('shift_2_end_time', models.TimeField(blank=True, null=True)),
                ('shift_2_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_3_start_time', models.TimeField(blank=True, null=True)),
                ('shift_3_end_time', models.TimeField(blank=True, null=True)),
                ('shift_3_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_4_start_time', models.TimeField(blank=True, null=True)),
                ('shift_4_end_time', models.TimeField(blank=True, null=True)),
                ('shift_4_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_5_start_time', models.TimeField(blank=True, null=True)),
                ('shift_5_end_time', models.TimeField(blank=True, null=True)),
                ('shift_5_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_6_start_time', models.TimeField(blank=True, null=True)),
                ('shift_6_end_time', models.TimeField(blank=True, null=True)),
                ('shift_6_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_7_start_time', models.TimeField(blank=True, null=True)),
                ('shift_7_end_time', models.TimeField(blank=True, null=True)),
                ('shift_7_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_8_start_time', models.TimeField(blank=True, null=True)),
                ('shift_8_end_time', models.TimeField(blank=True, null=True)),
                ('shift_8_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_9_start_time', models.TimeField(blank=True, null=True)),
                ('shift_9_end_time', models.TimeField(blank=True, null=True)),
                ('shift_9_job', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_10_start_time', models.TimeField(blank=True, null=True)),
                ('shift_10_end_time', models.TimeField(blank=True, null=True)),
                ('shift_10_job', models.CharField(blank=True, max_length=100, null=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_manage.employees')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_manage.jobs')),
            ],
        ),
    ]
