name: Python Package using Conda

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.0
    - name: Add pip to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        pip install django
